# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'birthdayonweek2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1133, 847)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(90, 90, 691, 681))
        self.tableWidget.setRowCount(10000)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.labelUser = QtWidgets.QLabel(Form)
        self.labelUser.setGeometry(QtCore.QRect(940, 50, 171, 21))
        self.labelUser.setStyleSheet("font: 12pt \"Cantarell\";\n"
"color: rgb(18, 10, 255);")
        self.labelUser.setObjectName("labelUser")
        self.headLabe = QtWidgets.QLabel(Form)
        self.headLabe.setGeometry(QtCore.QRect(240, 30, 431, 41))
        self.headLabe.setStyleSheet("font: 14pt \"Cantarell\";\n"
"font: 18pt \"Cantarell\";\n"
"color: rgb(43, 0, 255);")
        self.headLabe.setObjectName("headLabe")
        self.familyLabel = QtWidgets.QLabel(Form)
        self.familyLabel.setGeometry(QtCore.QRect(760, 730, 171, 41))
        self.familyLabel.setText("")
        self.familyLabel.setObjectName("familyLabel")
        self.cancelPushButton = QtWidgets.QPushButton(Form)
        self.cancelPushButton.setGeometry(QtCore.QRect(900, 150, 151, 41))
        self.cancelPushButton.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"Cantarell\";\n"
"background-color: red;")
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.HeadLabel = QtWidgets.QLabel(Form)
        self.HeadLabel.setGeometry(QtCore.QRect(810, 40, 121, 41))
        self.HeadLabel.setStyleSheet("font: 14pt \"Cantarell\";")
        self.HeadLabel.setObjectName("HeadLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Телефон"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Год р."))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Месяц р."))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "День р."))
        self.labelUser.setText(_translate("Form", "User"))
        self.headLabe.setText(_translate("Form", "Дни рождения в этом месяце"))
        self.cancelPushButton.setText(_translate("Form", "назад"))
        self.HeadLabel.setText(_translate("Form", "Зашли как:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
