# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(1175, 797)
        self.widget = QtWidgets.QWidget(LoginDialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1221, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.035, y1:0.0511364, x2:0.951327, y2:0.915, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(470, 100, 161, 131))
        self.label.setStyleSheet("\n"
"font: 28pt \"DejaVu Math TeX Gyre\";\n"
"color: rgb(170, 255, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(240, 220, 731, 71))
        self.label_2.setStyleSheet("color: rgb(255, 255, 127);\n"
"font: 24pt \"Cantarell\";")
        self.label_2.setObjectName("label_2")
        self.loginLoginDialog = QtWidgets.QPushButton(self.widget)
        self.loginLoginDialog.setGeometry(QtCore.QRect(420, 550, 271, 51))
        self.loginLoginDialog.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: rgb(124, 255, 235);")
        self.loginLoginDialog.setObjectName("loginLoginDialog")
        self.emailField = QtWidgets.QLineEdit(self.widget)
        self.emailField.setGeometry(QtCore.QRect(380, 350, 341, 41))
        self.emailField.setObjectName("emailField")
        self.passwordField = QtWidgets.QLineEdit(self.widget)
        self.passwordField.setGeometry(QtCore.QRect(380, 450, 341, 41))
        self.passwordField.setObjectName("passwordField")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(380, 320, 141, 20))
        self.label_3.setStyleSheet("font: 14pt \"Cantarell\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(380, 420, 141, 20))
        self.label_4.setStyleSheet("font: 14pt \"Cantarell\";")
        self.label_4.setObjectName("label_4")
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setGeometry(QtCore.QRect(380, 500, 341, 21))
        self.errorLabel.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color:rgb(255, 0, 0)")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.label.setText(_translate("LoginDialog", "Вход "))
        self.label_2.setText(_translate("LoginDialog", "Вход в существующий аккаунт"))
        self.loginLoginDialog.setText(_translate("LoginDialog", "Вход"))
        self.label_3.setText(_translate("LoginDialog", "UserName"))
        self.label_4.setText(_translate("LoginDialog", "Password"))
