# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fillprofile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fillProfileDialog(object):
    def setupUi(self, fillProfileDialog):
        fillProfileDialog.setObjectName("fillProfileDialog")
        fillProfileDialog.resize(1175, 797)
        self.widget = QtWidgets.QWidget(fillProfileDialog)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 1221, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.035, y1:0.0511364, x2:0.951327, y2:0.915, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.proflabel = QtWidgets.QLabel(self.widget)
        self.proflabel.setGeometry(QtCore.QRect(280, 50, 571, 131))
        self.proflabel.setStyleSheet("\n"
"font: 24pt \"DejaVu Math TeX Gyre\";\n"
"color: rgb(170, 255, 127);")
        self.proflabel.setObjectName("proflabel")
        self.messagelabel = QtWidgets.QLabel(self.widget)
        self.messagelabel.setGeometry(QtCore.QRect(280, 140, 741, 71))
        self.messagelabel.setStyleSheet("color: rgb(255, 255, 127);\n"
"font: 18pt \"Cantarell\";")
        self.messagelabel.setObjectName("messagelabel")
        self.continueButton = QtWidgets.QPushButton(self.widget)
        self.continueButton.setGeometry(QtCore.QRect(480, 710, 271, 51))
        self.continueButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: rgb(124, 255, 235);")
        self.continueButton.setObjectName("continueButton")
        self.emailField = QtWidgets.QLineEdit(self.widget)
        self.emailField.setGeometry(QtCore.QRect(270, 530, 341, 41))
        self.emailField.setObjectName("emailField")
        self.firstNameField = QtWidgets.QLineEdit(self.widget)
        self.firstNameField.setGeometry(QtCore.QRect(270, 630, 341, 41))
        self.firstNameField.setObjectName("firstNameField")
        self.userNameLabel = QtWidgets.QLabel(self.widget)
        self.userNameLabel.setGeometry(QtCore.QRect(270, 500, 141, 20))
        self.userNameLabel.setStyleSheet("font: 14pt \"Cantarell\";")
        self.userNameLabel.setObjectName("userNameLabel")
        self.firstNameLabel = QtWidgets.QLabel(self.widget)
        self.firstNameLabel.setGeometry(QtCore.QRect(270, 600, 141, 20))
        self.firstNameLabel.setStyleSheet("font: 14pt \"Cantarell\";")
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setGeometry(QtCore.QRect(380, 620, 341, 21))
        self.errorLabel.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color:rgb(255, 0, 0)")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.birthdayLabel = QtWidgets.QLabel(self.widget)
        self.birthdayLabel.setGeometry(QtCore.QRect(840, 600, 201, 20))
        self.birthdayLabel.setStyleSheet("font: 14pt \"Cantarell\";")
        self.birthdayLabel.setObjectName("birthdayLabel")
        self.lastNamePLabel = QtWidgets.QLabel(self.widget)
        self.lastNamePLabel.setGeometry(QtCore.QRect(670, 500, 201, 20))
        self.lastNamePLabel.setStyleSheet("font: 14pt \"Cantarell\";")
        self.lastNamePLabel.setObjectName("lastNamePLabel")
        self.lastNameField = QtWidgets.QLineEdit(self.widget)
        self.lastNameField.setGeometry(QtCore.QRect(670, 530, 341, 41))
        self.lastNameField.setObjectName("lastNameField")
        self.birthdaydateEdit = QtWidgets.QDateEdit(self.widget)
        self.birthdaydateEdit.setGeometry(QtCore.QRect(840, 630, 170, 36))
        self.birthdaydateEdit.setObjectName("birthdaydateEdit")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget)
        self.graphicsView.setGeometry(QtCore.QRect(360, 250, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.uploadpushButton = QtWidgets.QPushButton(self.widget)
        self.uploadpushButton.setGeometry(QtCore.QRect(670, 400, 113, 36))
        self.uploadpushButton.setObjectName("uploadpushButton")
        self.genderLabel = QtWidgets.QLabel(self.widget)
        self.genderLabel.setGeometry(QtCore.QRect(680, 600, 201, 20))
        self.genderLabel.setStyleSheet("font: 14pt \"Cantarell\";")
        self.genderLabel.setObjectName("genderLabel")
        self.gendercomboBox = QtWidgets.QComboBox(self.widget)
        self.gendercomboBox.setGeometry(QtCore.QRect(670, 630, 93, 36))
        self.gendercomboBox.setObjectName("gendercomboBox")

        self.retranslateUi(fillProfileDialog)
        QtCore.QMetaObject.connectSlotsByName(fillProfileDialog)

    def retranslateUi(self, fillProfileDialog):
        _translate = QtCore.QCoreApplication.translate
        fillProfileDialog.setWindowTitle(_translate("fillProfileDialog", "Dialog"))
        self.proflabel.setText(_translate("fillProfileDialog", "Заполните свой профиль "))
        self.messagelabel.setText(_translate("fillProfileDialog", "Теперь у вас есть аккаунь , заполните свой профиль"))
        self.continueButton.setText(_translate("fillProfileDialog", "Continue"))
        self.userNameLabel.setText(_translate("fillProfileDialog", "UserName"))
        self.firstNameLabel.setText(_translate("fillProfileDialog", "First Name"))
        self.birthdayLabel.setText(_translate("fillProfileDialog", "Birthday"))
        self.lastNamePLabel.setText(_translate("fillProfileDialog", "Last Name"))
        self.uploadpushButton.setText(_translate("fillProfileDialog", "UpLoad"))
        self.genderLabel.setText(_translate("fillProfileDialog", "Gender"))
