# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insertnewrecord.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InsertDialog(object):
    def setupUi(self, InsertDialog):
        InsertDialog.setObjectName("InsertDialog")
        InsertDialog.resize(1175, 797)
        self.widget = QtWidgets.QWidget(InsertDialog)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 1221, 801))
        self.widget.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.widget.setObjectName("widget")
        self.insertLabel = QtWidgets.QLabel(self.widget)
        self.insertLabel.setGeometry(QtCore.QRect(260, 50, 641, 131))
        self.insertLabel.setStyleSheet("font: 28pt \"DejaVu Math TeX Gyre\";\n"
"color: black;")
        self.insertLabel.setObjectName("insertLabel")
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setGeometry(QtCore.QRect(380, 460, 451, 71))
        self.errorLabel.setStyleSheet("color: red;\n"
"font: 18pt \"Cantarell\";\n"
"")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.insertPushButton = QtWidgets.QPushButton(self.widget)
        self.insertPushButton.setGeometry(QtCore.QRect(370, 690, 211, 51))
        self.insertPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: green;")
        self.insertPushButton.setObjectName("insertPushButton")
        self.nameField = QtWidgets.QLineEdit(self.widget)
        self.nameField.setGeometry(QtCore.QRect(370, 200, 461, 71))
        self.nameField.setObjectName("nameField")
        self.nomerField = QtWidgets.QLineEdit(self.widget)
        self.nomerField.setGeometry(QtCore.QRect(370, 290, 461, 71))
        self.nomerField.setObjectName("nomerField")
        self.dayField = QtWidgets.QLineEdit(self.widget)
        self.dayField.setGeometry(QtCore.QRect(370, 380, 461, 71))
        self.dayField.setObjectName("dayField")
        self.cancelPushButton = QtWidgets.QPushButton(self.widget)
        self.cancelPushButton.setGeometry(QtCore.QRect(640, 690, 191, 51))
        self.cancelPushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: red;")
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.yearField = QtWidgets.QLineEdit(self.widget)
        self.yearField.setGeometry(QtCore.QRect(370, 560, 461, 71))
        self.yearField.setObjectName("yearField")
        self.monthField = QtWidgets.QLineEdit(self.widget)
        self.monthField.setGeometry(QtCore.QRect(370, 470, 461, 71))
        self.monthField.setObjectName("monthField")

        self.retranslateUi(InsertDialog)
        QtCore.QMetaObject.connectSlotsByName(InsertDialog)

    def retranslateUi(self, InsertDialog):
        _translate = QtCore.QCoreApplication.translate
        InsertDialog.setWindowTitle(_translate("InsertDialog", "Dialog"))
        self.insertLabel.setText(_translate("InsertDialog", "Добавить новый контакт"))
        self.insertPushButton.setText(_translate("InsertDialog", "Добавить"))
        self.nameField.setPlaceholderText(_translate("InsertDialog", "   Фамилия"))
        self.nomerField.setPlaceholderText(_translate("InsertDialog", "   Номер телефона (10 цифр)"))
        self.dayField.setPlaceholderText(_translate("InsertDialog", "   День рождения"))
        self.cancelPushButton.setText(_translate("InsertDialog", "Отмена"))
        self.yearField.setPlaceholderText(_translate("InsertDialog", "   Год рождения"))
        self.monthField.setPlaceholderText(_translate("InsertDialog", "Месяц рождения"))
