# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTable(object):
    def setupUi(self, FormTable):
        FormTable.setObjectName("FormTable")
        FormTable.resize(1007, 790)
        self.tableWidget = QtWidgets.QTableWidget(FormTable)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 851, 751))
        self.tableWidget.setRowCount(5555)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.headerLabel = QtWidgets.QLabel(FormTable)
        self.headerLabel.setGeometry(QtCore.QRect(883, 20, 91, 101))
        self.headerLabel.setObjectName("headerLabel")

        self.retranslateUi(FormTable)
        QtCore.QMetaObject.connectSlotsByName(FormTable)

    def retranslateUi(self, FormTable):
        _translate = QtCore.QCoreApplication.translate
        FormTable.setWindowTitle(_translate("FormTable", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormTable", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormTable", "День рождения"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormTable", "Месяц рождения"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FormTable", "Год рождения"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FormTable", "Номер телефона"))
        self.headerLabel.setText(_translate("FormTable", "MyTable"))
