# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableDialog(object):
    def setupUi(self, TableDialog):
        TableDialog.setObjectName("TableDialog")
        TableDialog.resize(1172, 792)
        self.displayRowspushButton = QtWidgets.QPushButton(TableDialog)
        self.displayRowspushButton.setGeometry(QtCore.QRect(40, 20, 311, 41))
        self.displayRowspushButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: green;")
        self.displayRowspushButton.setObjectName("displayRowspushButton")
        self.allTableWidget = QtWidgets.QTableWidget(TableDialog)
        self.allTableWidget.setGeometry(QtCore.QRect(30, 80, 831, 321))
        self.allTableWidget.setRowCount(9999)
        self.allTableWidget.setColumnCount(5)
        self.allTableWidget.setObjectName("allTableWidget")
        self.HeadLabel = QtWidgets.QLabel(TableDialog)
        self.HeadLabel.setGeometry(QtCore.QRect(780, 30, 121, 21))
        self.HeadLabel.setStyleSheet("font: 14pt \"Cantarell\";")
        self.HeadLabel.setObjectName("HeadLabel")
        self.nameUserLabel = QtWidgets.QLabel(TableDialog)
        self.nameUserLabel.setGeometry(QtCore.QRect(930, 30, 201, 21))
        self.nameUserLabel.setStyleSheet("font: 14pt \"Cantarell\";\n"
"color: blue;")
        self.nameUserLabel.setText("")
        self.nameUserLabel.setObjectName("nameUserLabel")
        self.searchPushButton = QtWidgets.QPushButton(TableDialog)
        self.searchPushButton.setGeometry(QtCore.QRect(40, 710, 113, 36))
        self.searchPushButton.setObjectName("searchPushButton")
        self.nameLineEdit = QtWidgets.QLineEdit(TableDialog)
        self.nameLineEdit.setGeometry(QtCore.QRect(200, 710, 291, 36))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.familyLabel = QtWidgets.QLabel(TableDialog)
        self.familyLabel.setGeometry(QtCore.QRect(800, 710, 171, 41))
        self.familyLabel.setText("")
        self.familyLabel.setObjectName("familyLabel")
        self.selectTableWidget = QtWidgets.QTableWidget(TableDialog)
        self.selectTableWidget.setGeometry(QtCore.QRect(30, 410, 831, 291))
        self.selectTableWidget.setRowCount(10000)
        self.selectTableWidget.setColumnCount(5)
        self.selectTableWidget.setObjectName("selectTableWidget")

        self.retranslateUi(TableDialog)
        QtCore.QMetaObject.connectSlotsByName(TableDialog)

    def retranslateUi(self, TableDialog):
        _translate = QtCore.QCoreApplication.translate
        TableDialog.setWindowTitle(_translate("TableDialog", "Dialog"))
        self.displayRowspushButton.setText(_translate("TableDialog", "Показать все записи"))
        self.HeadLabel.setText(_translate("TableDialog", "Зашли как"))
        self.searchPushButton.setText(_translate("TableDialog", "Search"))
        self.nameLineEdit.setPlaceholderText(_translate("TableDialog", "   Введите имя"))
