# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableDialog(object):
    def setupUi(self, TableDialog):
        TableDialog.setObjectName("TableDialog")
        TableDialog.resize(872, 732)
        self.pushButtonDisplayRows = QtWidgets.QPushButton(TableDialog)
        self.pushButtonDisplayRows.setGeometry(QtCore.QRect(280, 120, 201, 41))
        self.pushButtonDisplayRows.setObjectName("pushButtonDisplayRows")
        self.tableWidget = QtWidgets.QTableWidget(TableDialog)
        self.tableWidget.setGeometry(QtCore.QRect(70, 200, 741, 501))
        self.tableWidget.setRowCount(999999)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")

        self.retranslateUi(TableDialog)
        QtCore.QMetaObject.connectSlotsByName(TableDialog)

    def retranslateUi(self, TableDialog):
        _translate = QtCore.QCoreApplication.translate
        TableDialog.setWindowTitle(_translate("TableDialog", "Dialog"))
        self.pushButtonDisplayRows.setText(_translate("TableDialog", "Display Rows"))
