# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1175, 797)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 1211, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.035, y1:0.0511364, x2:0.951327, y2:0.915, stop:0 rgba(0, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(310, 120, 551, 131))
        self.label.setStyleSheet("\n"
"font: 28pt \"DejaVu Math TeX Gyre\";\n"
"color: rgb(170, 255, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(240, 230, 731, 71))
        self.label_2.setStyleSheet("color: rgb(255, 255, 127);\n"
"font: 24pt \"Cantarell\";")
        self.label_2.setObjectName("label_2")
        self.loginDialog = QtWidgets.QPushButton(self.widget)
        self.loginDialog.setGeometry(QtCore.QRect(420, 360, 271, 51))
        self.loginDialog.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: rgb(124, 255, 235);")
        self.loginDialog.setObjectName("loginDialog")
        self.signupButton = QtWidgets.QPushButton(self.widget)
        self.signupButton.setGeometry(QtCore.QRect(420, 440, 271, 51))
        self.signupButton.setStyleSheet("border-radius:20px;\n"
"font: 18pt \"Cantarell\";\n"
"background-color: rgb(124, 255, 235);")
        self.signupButton.setObjectName("signupButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Добро пожаловать"))
        self.label_2.setText(_translate("Dialog", "Вход или регистрация пользователя"))
        self.loginDialog.setText(_translate("Dialog", "Вход"))
        self.signupButton.setText(_translate("Dialog", "Регистрация"))
