# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_autoshop.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import psycopg2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QTableWidget


class Ui_MyWidget(object):
    def setupUi(self, MyWidget):
        MyWidget.setObjectName("MyWidget")
        MyWidget.resize(881, 675)

        self.Tb = QtWidgets.QTableWidget(MyWidget)
        self.Tb.setGeometry(QtCore.QRect(20, 20, 661, 631))
        self.Tb.setRowCount(25)
        self.Tb.setObjectName("Tb")
        self.Tb.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.Tb.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tb.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tb.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tb.setHorizontalHeaderItem(3, item)
        self.addPushButton_1 = QtWidgets.QPushButton(MyWidget)
        self.addPushButton_1.setGeometry(QtCore.QRect(702, 300, 151, 36))
        self.addPushButton_1.setStyleSheet("font: 12pt \"Cantarell\";\n"
"color: rgb(32, 16, 255);\n"
"background-color: rgb(255, 109, 12);")
        self.addPushButton_1.setObjectName("addPushButton_1")
        self.delPushButton_2 = QtWidgets.QPushButton(MyWidget)
        self.delPushButton_2.setGeometry(QtCore.QRect(700, 350, 151, 36))
        self.delPushButton_2.setStyleSheet("font: 12pt \"Cantarell\";\n"
"color: rgb(32, 16, 255);\n"
"background-color: rgb(255, 109, 12);")
        self.delPushButton_2.setObjectName("delPushButton_2")
        self.renewPushButton_3 = QtWidgets.QPushButton(MyWidget)
        self.renewPushButton_3.setGeometry(QtCore.QRect(700, 400, 151, 36))
        self.renewPushButton_3.setStyleSheet("font: 12pt \"Cantarell\";\n"
"color: rgb(32, 16, 255);\n"
"background-color: rgb(255, 109, 12);")
        self.renewPushButton_3.setObjectName("renewPushButton_3")
        self.exitPushButton_4 = QtWidgets.QPushButton(MyWidget)
        self.exitPushButton_4.setGeometry(QtCore.QRect(700, 450, 151, 36))
        self.exitPushButton_4.setStyleSheet("font: 12pt \"Cantarell\";\n"
"color: rgb(32, 16, 255);\n"
"background-color: rgb(255, 109, 12);")
        self.exitPushButton_4.setObjectName("exitPushButton_4")
        self.idp_1 = QtWidgets.QLineEdit(MyWidget)
        self.idp_1.setGeometry(QtCore.QRect(710, 40, 141, 36))
        self.idp_1.setObjectName("idp_1")
        self.productname_2 = QtWidgets.QLineEdit(MyWidget)
        self.productname_2.setGeometry(QtCore.QRect(710, 90, 141, 36))
        self.productname_2.setObjectName("productname_2")
        self.quantity_3 = QtWidgets.QLineEdit(MyWidget)
        self.quantity_3.setGeometry(QtCore.QRect(710, 140, 141, 36))
        self.quantity_3.setObjectName("quantity_3")
        self.price_4 = QtWidgets.QLineEdit(MyWidget)
        self.price_4.setGeometry(QtCore.QRect(710, 200, 141, 36))
        self.price_4.setObjectName("price_4")

        self.retranslateUi(MyWidget)
        QtCore.QMetaObject.connectSlotsByName(MyWidget)


        self.con()
        self.updt()
        self.Tb.setEditTriggers(QTableWidget.NoEditTriggers)
        self.Tb.cellClicked.connect(self.cellClick)

    def con(self):
        self.conn = psycopg2.connect(user="user1",
                                     password="password1",
                                     host="127.0.0.1",
                                     port="5432",
                                     database="shopdb")
        self.cur = self.conn.cursor()


    def updt(self):
        self.Tb.clear()
        self.Tb.setRowCount(0)
        self.Tb.setHorizontalHeaderLabels(['id', 'Марка', 'Количество', 'Цена'])  # заголовки столцов
        self.cur.execute("select * from products2 order by id")
        rows = self.cur.fetchall()
        i = 0
        for elem in rows:
            self.Tb.setRowCount(self.Tb.rowCount() + 1)
            j = 0
            for t in elem:  # заполняем внутри строки
                self.Tb.setItem(i, j, QTableWidgetItem(str(t).strip()))
                j += 1
            i += 1
        self.Tb.resizeColumnsToContents()

    def retranslateUi(self, MyWidget):
        _translate = QtCore.QCoreApplication.translate
        MyWidget.setWindowTitle(_translate("MyWidget", "Form"))
        item = self.Tb.horizontalHeaderItem(0)
        item.setText(_translate("MyWidget", "id"))
        item = self.Tb.horizontalHeaderItem(1)
        item.setText(_translate("MyWidget", "Марка"))
        item = self.Tb.horizontalHeaderItem(2)
        item.setText(_translate("MyWidget", "Количество"))
        item = self.Tb.horizontalHeaderItem(3)
        item.setText(_translate("MyWidget", "Цена"))
        self.addPushButton_1.setText(_translate("MyWidget", "Добавить"))
        self.delPushButton_2.setText(_translate("MyWidget", "Удалить"))
        self.renewPushButton_3.setText(_translate("MyWidget", "Обновить"))
        self.exitPushButton_4.setText(_translate("MyWidget", "Выход"))

    # обработка щелчка мыши по таблице
    def cellClick(self, row, col, item):  # row - номер строки, col - номер столбца
        self.idp_1.setText(item(row, 0).text())
        self.productname_2.setText(self.item(row, 1).text().strip())
        self.quantity_3.setText(self.item(row, 2).text().strip())
        self.price_4.setText(self.item(row, 3).text().strip())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyWidget = QtWidgets.QWidget()
    ui = Ui_MyWidget()
    ui.setupUi(MyWidget)
    MyWidget.show()
    sys.exit(app.exec_())
