# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogfirst.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogFirst(object):
    def setupUi(self, DialogFirst):
        DialogFirst.setObjectName("DialogFirst")
        DialogFirst.resize(400, 300)
        self.labelFirst = QtWidgets.QLabel(DialogFirst)
        self.labelFirst.setGeometry(QtCore.QRect(130, 30, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelFirst.setFont(font)
        self.labelFirst.setObjectName("labelFirst")
        self.pushButtonFirst = QtWidgets.QPushButton(DialogFirst)
        self.pushButtonFirst.setGeometry(QtCore.QRect(92, 145, 221, 61))
        self.pushButtonFirst.setObjectName("pushButtonFirst")

        self.retranslateUi(DialogFirst)
        QtCore.QMetaObject.connectSlotsByName(DialogFirst)

    def retranslateUi(self, DialogFirst):
        _translate = QtCore.QCoreApplication.translate
        DialogFirst.setWindowTitle(_translate("DialogFirst", "Dialog"))
        self.labelFirst.setText(_translate("DialogFirst", "First window"))
        self.pushButtonFirst.setText(_translate("DialogFirst", "Открыть второе окно"))
