# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoRadioButton1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(727, 344)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.radioButtonFirstClass = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButtonFirstClass.setFont(font)
        self.radioButtonFirstClass.setObjectName("radioButtonFirstClass")
        self.verticalLayout.addWidget(self.radioButtonFirstClass)
        self.radioButtonBusinessClass = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButtonBusinessClass.setFont(font)
        self.radioButtonBusinessClass.setObjectName("radioButtonBusinessClass")
        self.verticalLayout.addWidget(self.radioButtonBusinessClass)
        self.radioButtonEconomClass = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButtonEconomClass.setFont(font)
        self.radioButtonEconomClass.setObjectName("radioButtonEconomClass")
        self.verticalLayout.addWidget(self.radioButtonEconomClass)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.labelFare = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelFare.setFont(font)
        self.labelFare.setText("")
        self.labelFare.setObjectName("labelFare")
        self.verticalLayout_2.addWidget(self.labelFare)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose the flight type"))
        self.radioButtonFirstClass.setText(_translate("Dialog", "First class 150$"))
        self.radioButtonBusinessClass.setText(_translate("Dialog", "Business class 125$"))
        self.radioButtonEconomClass.setText(_translate("Dialog", "Econom class $100"))
