# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoCheckBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(617, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 10, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelAmount = QtWidgets.QLabel(Dialog)
        self.labelAmount.setGeometry(QtCore.QRect(60, 260, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAmount.setFont(font)
        self.labelAmount.setObjectName("labelAmount")
        self.checkBoxChees = QtWidgets.QCheckBox(Dialog)
        self.checkBoxChees.setGeometry(QtCore.QRect(400, 30, 191, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBoxChees.setFont(font)
        self.checkBoxChees.setObjectName("checkBoxChees")
        self.checkBoxOliva = QtWidgets.QCheckBox(Dialog)
        self.checkBoxOliva.setGeometry(QtCore.QRect(400, 100, 191, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBoxOliva.setFont(font)
        self.checkBoxOliva.setObjectName("checkBoxOliva")
        self.echeckBoxSousaj = QtWidgets.QCheckBox(Dialog)
        self.echeckBoxSousaj.setGeometry(QtCore.QRect(400, 170, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.echeckBoxSousaj.setFont(font)
        self.echeckBoxSousaj.setObjectName("echeckBoxSousaj")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Regular pizza 10$"))
        self.labelAmount.setText(_translate("Dialog", "TextLabel"))
        self.checkBoxChees.setText(_translate("Dialog", "Extra cheez 1$"))
        self.checkBoxOliva.setText(_translate("Dialog", "extra oliva  2$"))
        self.echeckBoxSousaj.setText(_translate("Dialog", "sousaje 4$"))
        self.label_3.setText(_translate("Dialog", "Select your extra toppong"))
