# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(744, 485)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(280, 70, 302, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 140, 302, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(70, 230, 190, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 80, 302, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 140, 302, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(180, 340, 302, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.registrButton = QtWidgets.QPushButton(Form)
        self.registrButton.setGeometry(QtCore.QRect(270, 230, 190, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.registrButton.setFont(font)
        self.registrButton.setObjectName("registrButton")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(180, 300, 302, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.canselButton = QtWidgets.QPushButton(Form)
        self.canselButton.setGeometry(QtCore.QRect(470, 230, 190, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.canselButton.setFont(font)
        self.canselButton.setObjectName("canselButton")
        self.updateButton = QtWidgets.QPushButton(Form)
        self.updateButton.setGeometry(QtCore.QRect(212, 410, 351, 36))
        self.updateButton.setObjectName("updateButton")
        self.newRegistrButton = QtWidgets.QPushButton(Form)
        self.newRegistrButton.setGeometry(QtCore.QRect(520, 310, 201, 36))
        self.newRegistrButton.setObjectName("newRegistrButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "введите своё имя"))
        self.label_2.setText(_translate("Form", "Пароль"))
        self.loginButton.setText(_translate("Form", "Войти"))
        self.label.setText(_translate("Form", "Имя пользователя"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "введите свой пароль"))
        self.checkBox_2.setText(_translate("Form", "Показать пароль"))
        self.registrButton.setText(_translate("Form", "Регистрация"))
        self.checkBox.setText(_translate("Form", "Запомнить меня"))
        self.canselButton.setText(_translate("Form", "Отмена"))
        self.updateButton.setText(_translate("Form", "Забыли пароль ?"))
        self.newRegistrButton.setText(_translate("Form", "New Registr Window"))
